name: Publish Docker image
on:
  push:
    branches:
      - "develop"
jobs:
  get_semver:
    name: Create semver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
  build_and_push_dockerfile:
    name: Build the main docker image
    runs-on: ubuntu-latest
    needs: get_semver
    steps:
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.main-cache
          key: ${{ runner.os }}-main-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-main-
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./client/dockerfile
          pull: true
          push: true
          cache-from: type=local,src=/tmp/.main-cache
          cache-to: type=local,dest=/tmp/.main-cache-new
          tags: |
            ghcr.io/Centeva/osTicket:${{ needs.get_semver.outputs.semVer }}
            ghcr.io/Centeva/osTicket:latest
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move main cache
        run: |
          rm -rf /tmp/.main-cache
          mv /tmp/.main-cache-new /tmp/.main-cache
  create_tag:
    name: Push github tag
    runs-on: ubuntu-latest
    needs:
      - get_semver
      - build_and_push_dockerfile
    steps:
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ needs.get_semver.outputs.semVer }}",
              sha: context.sha
            })
